language: php

php:
  - 7.2
  - 7.3

services:
  - mysql

before_script:
  - cp .env.example .env
  - sudo mysql -e 'CREATE DATABASE afr;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate:refresh --seed --no-interaction -vvv
  - php artisan key:generate

script:
  - vendor/bin/phpunit --colors=always